[env:feather_nrf52840]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino

; --- ради экономии: DC/DC включен в коде, SoftDevice S140 ---
build_flags =
  -DCFG_DEBUG=0
  -DCONFIG_NFCT_PINS_AS_GPIOS

; Монитор для отладки по USB (на батарейке Serial молчит)
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

; UF2/Bossac прошивка по USB, J-Link не нужен
upload_protocol = nrfutil
upload_speed = 115200
